import { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  page: {
    backgroundColor: '#ffffff',
    color: '#111111',
    minHeight: '100vh',
    padding: '4rem',
  },
  content: {
    maxWidth: '1200px',
    margin: '0 auto',
  },
  title: {
    fontSize: '48px',
    marginBottom: '2.5rem',
    lineHeight: '1.2',
    color: '#111111',
  },
  paragraph: {
    fontSize: '22px',
    lineHeight: '1.6',
    marginBottom: '2rem',
    color: '#333333',
  },
  fileInput: {
    marginTop: '2rem',
    marginBottom: '2rem',
    display: 'block',
    fontSize: '18px',
    padding: '1rem',
    border: '2px solid #ccc',
    borderRadius: '8px',
    width: '100%',
    maxWidth: '500px',
  },
  youtubeLinkSection: {
    marginBottom: '2rem',
  },
  youtubeInput: {
    width: '100%',
    padding: '1rem',
    border: '2px solid #ccc',
    borderRadius: '8px',
    fontSize: '18px',
    maxWidth: '600px',
  },
  submitButton: {
    marginTop: '1rem',
    padding: '1.5rem 2.5rem',
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '20px',
    fontWeight: '500',
    transition: 'background-color 0.2s',
  },
  submitButtonDisabled: {
    backgroundColor: '#ccc',
    cursor: 'not-allowed',
    color: '#666',
  },
  successMessage: {
    color: 'green',
    marginTop: '1.5rem',
    fontSize: '20px',
    fontWeight: '500',
  },
  errorMessage: {
    color: 'red',
    marginTop: '1.5rem',
    fontSize: '20px',
    fontWeight: '500',
  },
  statusSection: {
    marginTop: '3rem',
    width: '100%',
  },
  sectionLabel: {
    fontSize: '20px',
    marginBottom: '1rem',
    marginTop: '2rem',
    color: '#333333',
  },
  input: {
    width: '100%',
    padding: '1rem',
    border: '1px solid #ccc',
    borderRadius: '8px',
    backgroundColor: '#f5f5f5',
    fontSize: '18px',
    maxWidth: '500px',
  },
  textarea: {
    width: '100%',
    height: '150px',
    padding: '1rem',
    border: '1px solid #ccc',
    borderRadius: '8px',
    backgroundColor: '#f5f5f5',
    fontSize: '18px',
    maxWidth: '800px',
    resize: 'vertical' as const,
  },
  backButton: {
    padding: '0.8rem 1.5rem',
    backgroundColor: '#f8f9fa',
    border: '2px solid #dee2e6',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '16px',
    fontWeight: '500',
    marginBottom: '2rem',
    color: '#495057',
    transition: 'all 0.2s',
  },
  submittedMessage: {
    backgroundColor: '#d4edda',
    border: '1px solid #c3e6cb',
    borderRadius: '8px',
    padding: '2rem',
    marginTop: '2rem',
    marginBottom: '2rem',
  },
  submittedText: {
    fontSize: '18px',
    color: '#155724',
    margin: '0.5rem 0',
  },
  link: {
    color: '#007bff',
    textDecoration: 'underline',
  },
};
