import { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  buttonStyle: {
    padding: '1.2rem 2.5rem',
    backgroundColor: '#e0e0e0',
    border: 'none',
    borderRadius: '8px',
    fontSize: '18px',
    cursor: 'pointer',
    fontWeight: '500',
  },
  signOutButtonStyle: {
    padding: '0.8rem 1.5rem',
    backgroundColor: '#dc3545',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '16px',
    cursor: 'pointer',
    fontWeight: '500',
    transition: 'background-color 0.2s',
  },
  projectTitleSectionStyle: {
    marginBottom: '3rem',
    borderBottom: '1px solid #e0e0e0',
    paddingBottom: '1.5rem',
  },
  projectTitleContainerStyle: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  projectTitleStyle: {
    fontSize: '28px',
    margin: 0,
    color: '#333',
    fontWeight: '500',
  },
  editButtonStyle: {
    padding: '0.4rem 0.8rem',
    backgroundColor: 'transparent',
    border: '1px solid #ccc',
    borderRadius: '4px',
    color: '#666',
    fontSize: '12px',
    cursor: 'pointer',
    fontWeight: '400',
    transition: 'all 0.2s',
  },
  editContainerStyle: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1rem',
    flex: 1,
  },
  titleInputStyle: {
    fontSize: '28px',
    padding: '0.5rem',
    border: '2px solid #007bff',
    borderRadius: '6px',
    fontWeight: '500',
    color: '#333',
    backgroundColor: '#ffffff',
    maxWidth: '600px',
    outline: 'none',
  },
  buttonGroupStyle: {
    display: 'flex',
    gap: '0.5rem',
  },
  saveButtonStyle: {
    padding: '0.5rem 1rem',
    backgroundColor: '#28a745',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    cursor: 'pointer',
    fontWeight: '500',
  },
  cancelButtonStyle: {
    padding: '0.5rem 1rem',
    backgroundColor: '#6c757d',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    cursor: 'pointer',
    fontWeight: '500',
  },
  dueDateCellStyle: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  dueDateEditButtonStyle: {
    padding: '0.2rem 0.4rem',
    backgroundColor: 'transparent',
    border: '1px solid #ccc',
    borderRadius: '3px',
    color: '#666',
    fontSize: '10px',
    cursor: 'pointer',
    fontWeight: '400',
    transition: 'all 0.2s',
  },
  dueDateEditContainerStyle: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  dueDateInputStyle: {
    padding: '0.3rem',
    border: '1px solid #007bff',
    borderRadius: '4px',
    fontSize: '14px',
    backgroundColor: '#ffffff',
    color: '#333',
    outline: 'none',
  },
  dueDateButtonGroupStyle: {
    display: 'flex',
    gap: '0.3rem',
  },
  dueDateSaveButtonStyle: {
    padding: '0.3rem 0.5rem',
    backgroundColor: '#28a745',
    color: 'white',
    border: 'none',
    borderRadius: '3px',
    fontSize: '12px',
    cursor: 'pointer',
    fontWeight: '500',
  },
  dueDateCancelButtonStyle: {
    padding: '0.3rem 0.5rem',
    backgroundColor: '#6c757d',
    color: 'white',
    border: 'none',
    borderRadius: '3px',
    fontSize: '12px',
    cursor: 'pointer',
    fontWeight: '500',
  },
};
