import { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    padding: '20px',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  header: {
    marginBottom: '20px',
  },
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    marginBottom: '10px',
  },
  projectInfo: {
    fontSize: '16px',
    color: '#666',
    marginBottom: '5px',
  },
  contentContainer: {
    display: 'flex',
    gap: '20px',
    flexDirection: 'column' as const,
  },
  viewerSection: {
    flex: 1,
    border: '1px solid #ddd',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  pdfContainer: {
    border: '1px solid #ddd',
    borderRadius: '8px',
    overflow: 'auto',
    maxHeight: '80vh',
    backgroundColor: '#f5f5f5',
    display: 'flex',
    justifyContent: 'center',
    padding: '20px',
  },
  pdfControls: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '10px',
    padding: '10px',
    backgroundColor: '#f5f5f5',
    borderBottom: '1px solid #ddd',
  },
  pageInfo: {
    minWidth: '100px',
    textAlign: 'center' as const,
  },
  controlButton: {
    padding: '8px 16px',
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  controlButtonDisabled: {
    padding: '8px 16px',
    backgroundColor: '#ccc',
    color: '#666',
    border: 'none',
    borderRadius: '4px',
    cursor: 'not-allowed',
  },
  youtubeSection: {
    padding: '20px',
    backgroundColor: '#f9f9f9',
    borderRadius: '8px',
  },
  youtubeTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    marginBottom: '10px',
  },
  youtubeLink: {
    color: '#007bff',
    textDecoration: 'none',
    fontSize: '14px',
    wordBreak: 'break-all' as const,
  },
  commentSection: {
    marginTop: '20px',
    padding: '20px',
    border: '1px solid #ddd',
    borderRadius: '8px',
    backgroundColor: '#fff',
  },
  commentLabel: {
    display: 'block',
    marginBottom: '10px',
    fontWeight: 'bold',
  },
  commentTextarea: {
    width: '100%',
    minHeight: '120px',
    padding: '10px',
    border: '1px solid #ddd',
    borderRadius: '4px',
    fontSize: '14px',
    fontFamily: 'inherit',
    resize: 'vertical' as const,
  },
  buttonContainer: {
    display: 'flex',
    gap: '10px',
    marginTop: '20px',
  },
  backButton: {
    padding: '10px 20px',
    backgroundColor: '#6c757d',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '16px',
  },
  saveButton: {
    padding: '10px 20px',
    backgroundColor: '#ffc107',
    color: '#000',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '16px',
  },
  saveButtonDisabled: {
    padding: '10px 20px',
    backgroundColor: '#ccc',
    color: '#666',
    border: 'none',
    borderRadius: '4px',
    cursor: 'not-allowed',
    fontSize: '16px',
  },
  approveButton: {
    padding: '10px 20px',
    backgroundColor: '#28a745',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '16px',
  },
  approveButtonDisabled: {
    padding: '10px 20px',
    backgroundColor: '#ccc',
    color: '#666',
    border: 'none',
    borderRadius: '4px',
    cursor: 'not-allowed',
    fontSize: '16px',
  },
  loading: {
    textAlign: 'center' as const,
    padding: '40px',
    fontSize: '18px',
    color: '#666',
  },
  error: {
    textAlign: 'center' as const,
    padding: '40px',
    fontSize: '18px',
    color: '#dc3545',
  },
  noSubmission: {
    textAlign: 'center' as const,
    padding: '40px',
    fontSize: '18px',
    color: '#666',
  },
};
