import { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    backgroundColor: '#ffffff',
    color: '#111111',
    minHeight: '100vh',
    padding: '3rem',
  },
  content: {
    maxWidth: '1400px',
    margin: '0 auto',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '3rem',
  },
  title: {
    fontSize: '42px',
    margin: 0,
    textAlign: 'left' as const,
  },
  signOutButton: {
    padding: '0.8rem 1.5rem',
    backgroundColor: '#dc3545',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '16px',
    cursor: 'pointer',
    fontWeight: '500',
    transition: 'background-color 0.2s',
  },
  tableContainer: {
    overflowX: 'auto' as const,
  },
  table: {
    width: '100%',
    fontSize: '16px',
    borderCollapse: 'collapse' as const,
    backgroundColor: 'white',
  },
  tableHeader: {
    textAlign: 'left' as const,
    paddingBottom: '1rem',
    fontWeight: '600',
    fontSize: '18px',
    borderBottom: '2px solid #dee2e6',
  },
  tableRow: {
    borderBottom: '1px solid #dee2e6',
  },
  tableCell: {
    padding: '1rem 0.5rem',
    textAlign: 'left' as const,
    fontSize: '16px',
    verticalAlign: 'middle',
  },
  actionButton: {
    padding: '0.5rem 1rem',
    backgroundColor: '#e0e0e0',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    cursor: 'pointer',
    fontWeight: '500',
    transition: 'background-color 0.2s',
    whiteSpace: 'nowrap',
  },
  projectTitleLink: {
    background: 'none',
    border: 'none',
    color: '#007bff',
    cursor: 'pointer',
    textDecoration: 'underline',
    fontSize: '16px',
    padding: 0,
    fontWeight: '500',
    transition: 'color 0.2s',
  },
  noProjects: {
    fontSize: '18px',
    textAlign: 'center' as const,
    marginTop: '3rem',
    color: '#666666',
  },
  teacherIdSection: {
    marginTop: '3rem',
    padding: '2rem',
    backgroundColor: '#f8f9fa',
    borderRadius: '8px',
    border: '1px solid #dee2e6',
  },
  teacherIdTitle: {
    fontSize: '20px',
    marginBottom: '0.5rem',
    color: '#111111',
  },
  teacherIdDescription: {
    fontSize: '16px',
    marginBottom: '1rem',
    color: '#666666',
  },
  teacherIdContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    flexWrap: 'wrap' as const,
  },
  teacherIdLabel: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#111111',
  },
  teacherId: {
    padding: '0.5rem 1rem',
    backgroundColor: '#ffffff',
    border: '1px solid #dee2e6',
    borderRadius: '4px',
    fontSize: '14px',
    fontFamily: 'monospace',
    color: '#495057',
    userSelect: 'all' as const,
  },
  copyButton: {
    padding: '0.5rem 1rem',
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
    fontWeight: '500',
    transition: 'background-color 0.2s',
  },
};
