-- =============================================
-- STORAGE POLICIES SETUP INSTRUCTIONS
-- =============================================
-- NOTE: Storage policies CANNOT be set via SQL Editor due to permissions.
-- You must configure them through the Supabase Dashboard UI.
--
-- Follow these steps instead:
-- =============================================

-- STEP-BY-STEP INSTRUCTIONS:
-- 
-- 1. Go to Storage in your Supabase Dashboard
-- 2. Click on "student-submissions" bucket
-- 3. Click "Policies" tab
-- 4. Click "New Policy"
-- 
-- CREATE THESE 4 POLICIES:
-- 
-- Policy 1: Upload Files
--   - Name: "Allow authenticated uploads"
--   - Allowed operation: INSERT
--   - Policy definition: 
--     (auth.role() = 'authenticated') AND (bucket_id = 'student-submissions')
-- 
-- Policy 2: Read Files
--   - Name: "Allow authenticated reads"
--   - Allowed operation: SELECT
--   - Policy definition:
--     (auth.role() = 'authenticated') AND (bucket_id = 'student-submissions')
-- 
-- Policy 3: Update Files
--   - Name: "Allow authenticated updates"
--   - Allowed operation: UPDATE
--   - Policy definition:
--     (auth.role() = 'authenticated') AND (bucket_id = 'student-submissions')
-- 
-- Policy 4: Delete Files
--   - Name: "Allow authenticated deletes"
--   - Allowed operation: DELETE
--   - Policy definition:
--     (auth.role() = 'authenticated') AND (bucket_id = 'student-submissions')
--
-- ALTERNATIVE: Use the "Quick Policies" templates:
-- - Click "New Policy" → "Allow all operations for authenticated users"
-- - This creates all 4 policies at once!
-- 
-- FOR THE RESOURCES BUCKET:
-- - The bucket is already public, so no additional policies needed
-- =============================================
